### ISSUE TITLE
Unattended Install / Command Line Parameters

### ISSUE THREAD

**Issue by Kickball** [iandrewt/MCInstall#2]
Change the script to allow for unattended install via passing of options through command line parameters.

**Comment by iandrewt** [comment]
Will add this in v1.1

**Comment by Kickball** [comment]
Do we have an estimated release date for 1.1?

**Comment by iandrewt** [comment]
By the end of next week, I've got a busy week with school this week

**Comment by Kickball** [comment]
Any updates?

**Comment by Kickball** [comment]
Do you still plan on completing this issue?

**Comment by iandrewt** [comment]
Sorry, I've abandoned this project temporarily so I can focus on school. I may work on it occasionally, however if you want to give it a crack and send a pull request, feel free.

**Comment by Kickball** [comment]
Added in 0bee2a2.
